FROM node:26-alpine AS builder

WORKDIR /app
COPY webserver/app/package*.json ./
COPY webserver/app/ .

COPY back/.env .env
RUN npm install --no-audit --no-fund --loglevel=error
RUN npm run build

FROM nginx:alpine AS runner

RUN apk add --no-cache openssl && \
    mkdir -p /etc/nginx/ssl

RUN openssl req -x509 -nodes -days 365 \
    -subj "/CN=localhost" \
    -newkey rsa:2048 \
    -keyout /etc/nginx/ssl/nginx.key \
    -out /etc/nginx/ssl/nginx.crt

COPY --from=builder /app/build /usr/share/nginx/html/app
COPY webserver/nginx/conf/nginx.conf /etc/nginx/nginx.conf

    
EXPOSE 80 443

CMD ["nginx", "-g", "daemon off;"]