-- AlterTable
ALTER TABLE "Payment" ALTER COLUMN "amount" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "User" ALTER COLUMN "budget" SET DEFAULT 1000,
ALTER COLUMN "budget" SET DATA TYPE DOUBLE PRECISION;
